courses/urls.py
from django.urls import path
from .views import IndexView, CourseListView, CourseDetailView, LessonDetailView


app_name =  'courses'

urlpatterns = [
    path('', IndexView.as_view(), name = 'index'),
    path('courses/', CourseListView.as_view(), name='course'),
    path('course/<slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('course/<course_slug>/<lesson_slug>/', LessonDetailView.as_view(), name='lesson_detail')
]

memberships/urls.py
from django.urls import path
from .views import UserProfileDetailView, UserProfileUpdateView, MembershipSelectView, PaymentView, stripe_webhook


app_name =  'memberships'

urlpatterns = [
	path('select/', MembershipSelectView.as_view(), name='select'),
	path('profile/<username>/', UserProfileDetailView.as_view(), name='profile'),
	path('profile/<username>/update/', UserProfileUpdateView.as_view(), name='profile_update'),
	path('payment/', PaymentView, name='payment'),
    path('stripe_webhook/', stripe_webhook, name='stripe_webhook'),

]

saas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('membership/', include('memberships.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/navbar.html
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" class="nav-link px-2 text-danger">Home</a></li>
          <li><a href="{% url 'courses:course' %}" class="nav-link px-2 text-white">Courses</a></li>
              {% block post_detail_link %}
              {% endblock post_detail_link %}
        </ul>

        <div class="text-end">
          {% if user.is_authenticated %}
          <a href="{% url 'memberships:select' %}"><button type="button" class="btn btn-warning">Memberships</button></a>
          <a href="{% url 'memberships:profile' user.username %}"><button type="button" class="btn btn-warning">Profile</button></a>
          <a href="{% url 'account_logout' %}"><button type="button" class="btn btn-outline-light me-2">Logout</button></a>
          {% else %}
          <a href="{% url 'account_login' %}"><button type="button" class="btn btn-outline-light me-2">Login</button></a>
          <a href="{% url 'account_signup' %}"><button type="button" class="btn btn-warning">Sign-up</button></a>
          {% endif %}
        </div>
      </div>
    </div>
  </header>